// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/chat/chat_service.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GroupRequest, GroupResponse, HistoryRequest, Message, MessageRequest, MessageResponse, StreamRequest, UserGroupsRequest, UserGroupsResponse } from "./chat_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service de messagerie
 *
 * @generated from service chat.ChatService
 */
export const ChatService = {
  typeName: "chat.ChatService",
  methods: {
    /**
     * @generated from rpc chat.ChatService.SendMessage
     */
    sendMessage: {
      name: "SendMessage",
      I: MessageRequest,
      O: MessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.GetMessageHistory
     */
    getMessageHistory: {
      name: "GetMessageHistory",
      I: HistoryRequest,
      O: Message,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc chat.ChatService.StreamMessages
     */
    streamMessages: {
      name: "StreamMessages",
      I: StreamRequest,
      O: Message,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc chat.ChatService.CreateGroup
     */
    createGroup: {
      name: "CreateGroup",
      I: GroupRequest,
      O: GroupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.GetUserGroups
     */
    getUserGroups: {
      name: "GetUserGroups",
      I: UserGroupsRequest,
      O: UserGroupsResponse,
      kind: MethodKind.Unary,
    },
  }
};

