// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=ts"
// @generated from file protos/chat/chat_service.proto (package chat, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file protos/chat/chat_service.proto.
 */
export declare const file_protos_chat_chat_service: GenFile;

/**
 * Messages pour l'envoi de messages
 *
 * @generated from message chat.MessageRequest
 */
export declare type MessageRequest = Message$1<"chat.MessageRequest"> & {
  /**
   * @generated from field: string senderId = 1;
   */
  senderId: string;

  /**
   * Peut être un userId ou un groupId
   *
   * @generated from field: string receiverId = 2;
   */
  receiverId: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: bool isGroup = 4;
   */
  isGroup: boolean;
};

/**
 * Describes the message chat.MessageRequest.
 * Use `create(MessageRequestSchema)` to create a new message.
 */
export declare const MessageRequestSchema: GenMessage<MessageRequest>;

/**
 * @generated from message chat.MessageResponse
 */
export declare type MessageResponse = Message$1<"chat.MessageResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string messageId = 2;
   */
  messageId: string;

  /**
   * @generated from field: string timestamp = 3;
   */
  timestamp: string;
};

/**
 * Describes the message chat.MessageResponse.
 * Use `create(MessageResponseSchema)` to create a new message.
 */
export declare const MessageResponseSchema: GenMessage<MessageResponse>;

/**
 * Messages pour l'historique
 *
 * @generated from message chat.HistoryRequest
 */
export declare type HistoryRequest = Message$1<"chat.HistoryRequest"> & {
  /**
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * Peut être un userId ou un groupId
   *
   * @generated from field: string targetId = 2;
   */
  targetId: string;

  /**
   * @generated from field: bool isGroup = 3;
   */
  isGroup: boolean;

  /**
   * @generated from field: int32 limit = 4;
   */
  limit: number;
};

/**
 * Describes the message chat.HistoryRequest.
 * Use `create(HistoryRequestSchema)` to create a new message.
 */
export declare const HistoryRequestSchema: GenMessage<HistoryRequest>;

/**
 * Messages pour le streaming en temps réel
 *
 * @generated from message chat.StreamRequest
 */
export declare type StreamRequest = Message$1<"chat.StreamRequest"> & {
  /**
   * @generated from field: string userId = 1;
   */
  userId: string;
};

/**
 * Describes the message chat.StreamRequest.
 * Use `create(StreamRequestSchema)` to create a new message.
 */
export declare const StreamRequestSchema: GenMessage<StreamRequest>;

/**
 * Structure de message
 *
 * @generated from message chat.Message
 */
export declare type Message = Message$1<"chat.Message"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string senderId = 2;
   */
  senderId: string;

  /**
   * @generated from field: string senderName = 3;
   */
  senderName: string;

  /**
   * @generated from field: string receiverId = 4;
   */
  receiverId: string;

  /**
   * @generated from field: string content = 5;
   */
  content: string;

  /**
   * @generated from field: string timestamp = 6;
   */
  timestamp: string;

  /**
   * @generated from field: bool isGroup = 7;
   */
  isGroup: boolean;
};

/**
 * Describes the message chat.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * Messages pour la gestion des groupes
 *
 * @generated from message chat.GroupRequest
 */
export declare type GroupRequest = Message$1<"chat.GroupRequest"> & {
  /**
   * @generated from field: string creatorId = 1;
   */
  creatorId: string;

  /**
   * @generated from field: string groupName = 2;
   */
  groupName: string;

  /**
   * @generated from field: repeated string memberIds = 3;
   */
  memberIds: string[];
};

/**
 * Describes the message chat.GroupRequest.
 * Use `create(GroupRequestSchema)` to create a new message.
 */
export declare const GroupRequestSchema: GenMessage<GroupRequest>;

/**
 * @generated from message chat.GroupResponse
 */
export declare type GroupResponse = Message$1<"chat.GroupResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string groupId = 2;
   */
  groupId: string;

  /**
   * @generated from field: string groupName = 3;
   */
  groupName: string;
};

/**
 * Describes the message chat.GroupResponse.
 * Use `create(GroupResponseSchema)` to create a new message.
 */
export declare const GroupResponseSchema: GenMessage<GroupResponse>;

/**
 * @generated from message chat.UserGroupsRequest
 */
export declare type UserGroupsRequest = Message$1<"chat.UserGroupsRequest"> & {
  /**
   * @generated from field: string userId = 1;
   */
  userId: string;
};

/**
 * Describes the message chat.UserGroupsRequest.
 * Use `create(UserGroupsRequestSchema)` to create a new message.
 */
export declare const UserGroupsRequestSchema: GenMessage<UserGroupsRequest>;

/**
 * @generated from message chat.UserGroupsResponse
 */
export declare type UserGroupsResponse = Message$1<"chat.UserGroupsResponse"> & {
  /**
   * @generated from field: repeated chat.Group groups = 1;
   */
  groups: Group[];
};

/**
 * Describes the message chat.UserGroupsResponse.
 * Use `create(UserGroupsResponseSchema)` to create a new message.
 */
export declare const UserGroupsResponseSchema: GenMessage<UserGroupsResponse>;

/**
 * @generated from message chat.Group
 */
export declare type Group = Message$1<"chat.Group"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string creatorId = 3;
   */
  creatorId: string;

  /**
   * @generated from field: repeated string memberIds = 4;
   */
  memberIds: string[];
};

/**
 * Describes the message chat.Group.
 * Use `create(GroupSchema)` to create a new message.
 */
export declare const GroupSchema: GenMessage<Group>;

/**
 * Service de messagerie
 *
 * @generated from service chat.ChatService
 */
export declare const ChatService: GenService<{
  /**
   * @generated from rpc chat.ChatService.SendMessage
   */
  sendMessage: {
    methodKind: "unary";
    input: typeof MessageRequestSchema;
    output: typeof MessageResponseSchema;
  },
  /**
   * @generated from rpc chat.ChatService.GetMessageHistory
   */
  getMessageHistory: {
    methodKind: "server_streaming";
    input: typeof HistoryRequestSchema;
    output: typeof MessageSchema;
  },
  /**
   * @generated from rpc chat.ChatService.StreamMessages
   */
  streamMessages: {
    methodKind: "server_streaming";
    input: typeof StreamRequestSchema;
    output: typeof MessageSchema;
  },
  /**
   * @generated from rpc chat.ChatService.CreateGroup
   */
  createGroup: {
    methodKind: "unary";
    input: typeof GroupRequestSchema;
    output: typeof GroupResponseSchema;
  },
  /**
   * @generated from rpc chat.ChatService.GetUserGroups
   */
  getUserGroups: {
    methodKind: "unary";
    input: typeof UserGroupsRequestSchema;
    output: typeof UserGroupsResponseSchema;
  },
}>;

