// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/chat/chat_service.proto (package chat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GroupRequest, GroupResponse, HistoryRequest, Message, MessageRequest, MessageResponse, StreamRequest, UserGroupsRequest, UserGroupsResponse } from "./chat_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service de messagerie
 *
 * @generated from service chat.ChatService
 */
export declare const ChatService: {
  readonly typeName: "chat.ChatService",
  readonly methods: {
    /**
     * @generated from rpc chat.ChatService.SendMessage
     */
    readonly sendMessage: {
      readonly name: "SendMessage",
      readonly I: typeof MessageRequest,
      readonly O: typeof MessageResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.GetMessageHistory
     */
    readonly getMessageHistory: {
      readonly name: "GetMessageHistory",
      readonly I: typeof HistoryRequest,
      readonly O: typeof Message,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc chat.ChatService.StreamMessages
     */
    readonly streamMessages: {
      readonly name: "StreamMessages",
      readonly I: typeof StreamRequest,
      readonly O: typeof Message,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc chat.ChatService.CreateGroup
     */
    readonly createGroup: {
      readonly name: "CreateGroup",
      readonly I: typeof GroupRequest,
      readonly O: typeof GroupResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chat.ChatService.GetUserGroups
     */
    readonly getUserGroups: {
      readonly name: "GetUserGroups",
      readonly I: typeof UserGroupsRequest,
      readonly O: typeof UserGroupsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

