// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=ts"
// @generated from file protos/chat/chat_service.proto (package chat, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file protos/chat/chat_service.proto.
 */
export const file_protos_chat_chat_service = /*@__PURE__*/
  fileDesc("Ch5wcm90b3MvY2hhdC9jaGF0X3NlcnZpY2UucHJvdG8SBGNoYXQiWAoOTWVzc2FnZVJlcXVlc3QSEAoIc2VuZGVySWQYASABKAkSEgoKcmVjZWl2ZXJJZBgCIAEoCRIPCgdjb250ZW50GAMgASgJEg8KB2lzR3JvdXAYBCABKAgiSAoPTWVzc2FnZVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSEQoJbWVzc2FnZUlkGAIgASgJEhEKCXRpbWVzdGFtcBgDIAEoCSJSCg5IaXN0b3J5UmVxdWVzdBIOCgZ1c2VySWQYASABKAkSEAoIdGFyZ2V0SWQYAiABKAkSDwoHaXNHcm91cBgDIAEoCBINCgVsaW1pdBgEIAEoBSIfCg1TdHJlYW1SZXF1ZXN0Eg4KBnVzZXJJZBgBIAEoCSKEAQoHTWVzc2FnZRIKCgJpZBgBIAEoCRIQCghzZW5kZXJJZBgCIAEoCRISCgpzZW5kZXJOYW1lGAMgASgJEhIKCnJlY2VpdmVySWQYBCABKAkSDwoHY29udGVudBgFIAEoCRIRCgl0aW1lc3RhbXAYBiABKAkSDwoHaXNHcm91cBgHIAEoCCJHCgxHcm91cFJlcXVlc3QSEQoJY3JlYXRvcklkGAEgASgJEhEKCWdyb3VwTmFtZRgCIAEoCRIRCgltZW1iZXJJZHMYAyADKAkiRAoNR3JvdXBSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB2dyb3VwSWQYAiABKAkSEQoJZ3JvdXBOYW1lGAMgASgJIiMKEVVzZXJHcm91cHNSZXF1ZXN0Eg4KBnVzZXJJZBgBIAEoCSIxChJVc2VyR3JvdXBzUmVzcG9uc2USGwoGZ3JvdXBzGAEgAygLMgsuY2hhdC5Hcm91cCJHCgVHcm91cBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhEKCWNyZWF0b3JJZBgDIAEoCRIRCgltZW1iZXJJZHMYBCADKAkyuQIKC0NoYXRTZXJ2aWNlEjoKC1NlbmRNZXNzYWdlEhQuY2hhdC5NZXNzYWdlUmVxdWVzdBoVLmNoYXQuTWVzc2FnZVJlc3BvbnNlEjoKEUdldE1lc3NhZ2VIaXN0b3J5EhQuY2hhdC5IaXN0b3J5UmVxdWVzdBoNLmNoYXQuTWVzc2FnZTABEjYKDlN0cmVhbU1lc3NhZ2VzEhMuY2hhdC5TdHJlYW1SZXF1ZXN0Gg0uY2hhdC5NZXNzYWdlMAESNgoLQ3JlYXRlR3JvdXASEi5jaGF0Lkdyb3VwUmVxdWVzdBoTLmNoYXQuR3JvdXBSZXNwb25zZRJCCg1HZXRVc2VyR3JvdXBzEhcuY2hhdC5Vc2VyR3JvdXBzUmVxdWVzdBoYLmNoYXQuVXNlckdyb3Vwc1Jlc3BvbnNlQhwKDWNvbS5hZGlhLmNoYXRCCUNoYXRQcm90b1ABYgZwcm90bzM");

/**
 * Describes the message chat.MessageRequest.
 * Use `create(MessageRequestSchema)` to create a new message.
 */
export const MessageRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 0);

/**
 * Describes the message chat.MessageResponse.
 * Use `create(MessageResponseSchema)` to create a new message.
 */
export const MessageResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 1);

/**
 * Describes the message chat.HistoryRequest.
 * Use `create(HistoryRequestSchema)` to create a new message.
 */
export const HistoryRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 2);

/**
 * Describes the message chat.StreamRequest.
 * Use `create(StreamRequestSchema)` to create a new message.
 */
export const StreamRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 3);

/**
 * Describes the message chat.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 4);

/**
 * Describes the message chat.GroupRequest.
 * Use `create(GroupRequestSchema)` to create a new message.
 */
export const GroupRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 5);

/**
 * Describes the message chat.GroupResponse.
 * Use `create(GroupResponseSchema)` to create a new message.
 */
export const GroupResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 6);

/**
 * Describes the message chat.UserGroupsRequest.
 * Use `create(UserGroupsRequestSchema)` to create a new message.
 */
export const UserGroupsRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 7);

/**
 * Describes the message chat.UserGroupsResponse.
 * Use `create(UserGroupsResponseSchema)` to create a new message.
 */
export const UserGroupsResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 8);

/**
 * Describes the message chat.Group.
 * Use `create(GroupSchema)` to create a new message.
 */
export const GroupSchema = /*@__PURE__*/
  messageDesc(file_protos_chat_chat_service, 9);

/**
 * Service de messagerie
 *
 * @generated from service chat.ChatService
 */
export const ChatService = /*@__PURE__*/
  serviceDesc(file_protos_chat_chat_service, 0);

