// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file admin/admin.proto (package com.adia.admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admin/admin.proto.
 */
export const file_admin_admin: GenFile = /*@__PURE__*/
  fileDesc("ChFhZG1pbi9hZG1pbi5wcm90bxIOY29tLmFkaWEuYWRtaW4iHAoMQ2hlY2tSZXF1ZXN0EgwKBGRhdGEYASABKAkiMAoNQ2hlY2tSZXNwb25zZRIOCgZzdGF0dXMYASABKAgSDwoHbWVzc2FnZRgCIAEoCSIuCg9Vc2VyTGlzdFJlcXVlc3QSDAoEcGFnZRgBIAEoBRINCgVsaW1pdBgCIAEoBSJGChBVc2VyTGlzdFJlc3BvbnNlEiMKBXVzZXJzGAEgAygLMhQuY29tLmFkaWEuYWRtaW4uVXNlchINCgV0b3RhbBgCIAEoBSJEChFVc2VyQWN0aW9uUmVxdWVzdBIOCgZ1c2VySWQYASABKAkSDwoHYWRtaW5JZBgCIAEoCRIOCgZyZWFzb24YAyABKAkiNgoSVXNlckFjdGlvblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCSJKChRNZXNzYWdlQWN0aW9uUmVxdWVzdBIRCgltZXNzYWdlSWQYASABKAkSDwoHYWRtaW5JZBgCIAEoCRIOCgZyZWFzb24YAyABKAkiOQoVTWVzc2FnZUFjdGlvblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCSJmCgRVc2VyEgoKAmlkGAEgASgJEg0KBWVtYWlsGAIgASgJEhAKCHVzZXJuYW1lGAMgASgJEgwKBHJvbGUYBCABKAkSEAoIaXNCYW5uZWQYBSABKAgSEQoJY3JlYXRlZEF0GAYgASgJMtYCCgxBZG1pblNlcnZpY2USUAoLR2V0QWxsVXNlcnMSHy5jb20uYWRpYS5hZG1pbi5Vc2VyTGlzdFJlcXVlc3QaIC5jb20uYWRpYS5hZG1pbi5Vc2VyTGlzdFJlc3BvbnNlElAKB0JhblVzZXISIS5jb20uYWRpYS5hZG1pbi5Vc2VyQWN0aW9uUmVxdWVzdBoiLmNvbS5hZGlhLmFkbWluLlVzZXJBY3Rpb25SZXNwb25zZRJcCg1EZWxldGVNZXNzYWdlEiQuY29tLmFkaWEuYWRtaW4uTWVzc2FnZUFjdGlvblJlcXVlc3QaJS5jb20uYWRpYS5hZG1pbi5NZXNzYWdlQWN0aW9uUmVzcG9uc2USRAoFQ2hlY2sSHC5jb20uYWRpYS5hZG1pbi5DaGVja1JlcXVlc3QaHS5jb20uYWRpYS5hZG1pbi5DaGVja1Jlc3BvbnNlQh4KDmNvbS5hZGlhLmFkbWluQgpBZG1pblByb3RvUAFiBnByb3RvMw");

/**
 * @generated from message com.adia.admin.CheckRequest
 */
export type CheckRequest = Message<"com.adia.admin.CheckRequest"> & {
  /**
   * @generated from field: string data = 1;
   */
  data: string;
};

/**
 * Describes the message com.adia.admin.CheckRequest.
 * Use `create(CheckRequestSchema)` to create a new message.
 */
export const CheckRequestSchema: GenMessage<CheckRequest> = /*@__PURE__*/
  messageDesc(file_admin_admin, 0);

/**
 * @generated from message com.adia.admin.CheckResponse
 */
export type CheckResponse = Message<"com.adia.admin.CheckResponse"> & {
  /**
   * @generated from field: bool status = 1;
   */
  status: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message com.adia.admin.CheckResponse.
 * Use `create(CheckResponseSchema)` to create a new message.
 */
export const CheckResponseSchema: GenMessage<CheckResponse> = /*@__PURE__*/
  messageDesc(file_admin_admin, 1);

/**
 * Messages pour la gestion des utilisateurs
 *
 * @generated from message com.adia.admin.UserListRequest
 */
export type UserListRequest = Message<"com.adia.admin.UserListRequest"> & {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message com.adia.admin.UserListRequest.
 * Use `create(UserListRequestSchema)` to create a new message.
 */
export const UserListRequestSchema: GenMessage<UserListRequest> = /*@__PURE__*/
  messageDesc(file_admin_admin, 2);

/**
 * @generated from message com.adia.admin.UserListResponse
 */
export type UserListResponse = Message<"com.adia.admin.UserListResponse"> & {
  /**
   * @generated from field: repeated com.adia.admin.User users = 1;
   */
  users: User[];

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;
};

/**
 * Describes the message com.adia.admin.UserListResponse.
 * Use `create(UserListResponseSchema)` to create a new message.
 */
export const UserListResponseSchema: GenMessage<UserListResponse> = /*@__PURE__*/
  messageDesc(file_admin_admin, 3);

/**
 * @generated from message com.adia.admin.UserActionRequest
 */
export type UserActionRequest = Message<"com.adia.admin.UserActionRequest"> & {
  /**
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * @generated from field: string adminId = 2;
   */
  adminId: string;

  /**
   * @generated from field: string reason = 3;
   */
  reason: string;
};

/**
 * Describes the message com.adia.admin.UserActionRequest.
 * Use `create(UserActionRequestSchema)` to create a new message.
 */
export const UserActionRequestSchema: GenMessage<UserActionRequest> = /*@__PURE__*/
  messageDesc(file_admin_admin, 4);

/**
 * @generated from message com.adia.admin.UserActionResponse
 */
export type UserActionResponse = Message<"com.adia.admin.UserActionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message com.adia.admin.UserActionResponse.
 * Use `create(UserActionResponseSchema)` to create a new message.
 */
export const UserActionResponseSchema: GenMessage<UserActionResponse> = /*@__PURE__*/
  messageDesc(file_admin_admin, 5);

/**
 * Messages pour la gestion des messages
 *
 * @generated from message com.adia.admin.MessageActionRequest
 */
export type MessageActionRequest = Message<"com.adia.admin.MessageActionRequest"> & {
  /**
   * @generated from field: string messageId = 1;
   */
  messageId: string;

  /**
   * @generated from field: string adminId = 2;
   */
  adminId: string;

  /**
   * @generated from field: string reason = 3;
   */
  reason: string;
};

/**
 * Describes the message com.adia.admin.MessageActionRequest.
 * Use `create(MessageActionRequestSchema)` to create a new message.
 */
export const MessageActionRequestSchema: GenMessage<MessageActionRequest> = /*@__PURE__*/
  messageDesc(file_admin_admin, 6);

/**
 * @generated from message com.adia.admin.MessageActionResponse
 */
export type MessageActionResponse = Message<"com.adia.admin.MessageActionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message com.adia.admin.MessageActionResponse.
 * Use `create(MessageActionResponseSchema)` to create a new message.
 */
export const MessageActionResponseSchema: GenMessage<MessageActionResponse> = /*@__PURE__*/
  messageDesc(file_admin_admin, 7);

/**
 * Structure d'utilisateur
 *
 * @generated from message com.adia.admin.User
 */
export type User = Message<"com.adia.admin.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: string role = 4;
   */
  role: string;

  /**
   * @generated from field: bool isBanned = 5;
   */
  isBanned: boolean;

  /**
   * @generated from field: string createdAt = 6;
   */
  createdAt: string;
};

/**
 * Describes the message com.adia.admin.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_admin_admin, 8);

/**
 * Service d'administration
 *
 * @generated from service com.adia.admin.AdminService
 */
export const AdminService: GenService<{
  /**
   * @generated from rpc com.adia.admin.AdminService.GetAllUsers
   */
  getAllUsers: {
    methodKind: "unary";
    input: typeof UserListRequestSchema;
    output: typeof UserListResponseSchema;
  },
  /**
   * @generated from rpc com.adia.admin.AdminService.BanUser
   */
  banUser: {
    methodKind: "unary";
    input: typeof UserActionRequestSchema;
    output: typeof UserActionResponseSchema;
  },
  /**
   * @generated from rpc com.adia.admin.AdminService.DeleteMessage
   */
  deleteMessage: {
    methodKind: "unary";
    input: typeof MessageActionRequestSchema;
    output: typeof MessageActionResponseSchema;
  },
  /**
   * @generated from rpc com.adia.admin.AdminService.Check
   */
  check: {
    methodKind: "unary";
    input: typeof CheckRequestSchema;
    output: typeof CheckResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_admin_admin, 0);

