// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=ts"
// @generated from file protos/notification/notification_service.proto (package notification, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file protos/notification/notification_service.proto.
 */
export const file_protos_notification_notification_service = /*@__PURE__*/
  fileDesc("Ci5wcm90b3Mvbm90aWZpY2F0aW9uL25vdGlmaWNhdGlvbl9zZXJ2aWNlLnByb3RvEgxub3RpZmljYXRpb24iJQoTU3Vic2NyaXB0aW9uUmVxdWVzdBIOCgZ1c2VySWQYASABKAkieQoMTm90aWZpY2F0aW9uEgoKAmlkGAEgASgJEg4KBnVzZXJJZBgCIAEoCRINCgV0aXRsZRgDIAEoCRIPCgdjb250ZW50GAQgASgJEgwKBHR5cGUYBSABKAkSEQoJdGltZXN0YW1wGAYgASgJEgwKBHJlYWQYByABKAgiZgobTm90aWZpY2F0aW9uU2V0dGluZ3NSZXF1ZXN0Eg4KBnVzZXJJZBgBIAEoCRITCgtlbmFibGVTb3VuZBgCIAEoCBIiChplbmFibGVEZXNrdG9wTm90aWZpY2F0aW9ucxgDIAEoCCIvChxOb3RpZmljYXRpb25TZXR0aW5nc1Jlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgy2AEKE05vdGlmaWNhdGlvblNlcnZpY2USTAoJU3Vic2NyaWJlEiEubm90aWZpY2F0aW9uLlN1YnNjcmlwdGlvblJlcXVlc3QaGi5ub3RpZmljYXRpb24uTm90aWZpY2F0aW9uMAEScwoaVXBkYXRlTm90aWZpY2F0aW9uU2V0dGluZ3MSKS5ub3RpZmljYXRpb24uTm90aWZpY2F0aW9uU2V0dGluZ3NSZXF1ZXN0Gioubm90aWZpY2F0aW9uLk5vdGlmaWNhdGlvblNldHRpbmdzUmVzcG9uc2VCLAoVY29tLmNoYXQubm90aWZpY2F0aW9uQhFOb3RpZmljYXRpb25Qcm90b1ABYgZwcm90bzM");

/**
 * Describes the message notification.SubscriptionRequest.
 * Use `create(SubscriptionRequestSchema)` to create a new message.
 */
export const SubscriptionRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_notification_notification_service, 0);

/**
 * Describes the message notification.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export const NotificationSchema = /*@__PURE__*/
  messageDesc(file_protos_notification_notification_service, 1);

/**
 * Describes the message notification.NotificationSettingsRequest.
 * Use `create(NotificationSettingsRequestSchema)` to create a new message.
 */
export const NotificationSettingsRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_notification_notification_service, 2);

/**
 * Describes the message notification.NotificationSettingsResponse.
 * Use `create(NotificationSettingsResponseSchema)` to create a new message.
 */
export const NotificationSettingsResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_notification_notification_service, 3);

/**
 * Service de notifications
 *
 * @generated from service notification.NotificationService
 */
export const NotificationService = /*@__PURE__*/
  serviceDesc(file_protos_notification_notification_service, 0);

