// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/notification/notification_service.proto (package notification, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Notification, NotificationSettingsRequest, NotificationSettingsResponse, SubscriptionRequest } from "./notification_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service de notifications
 *
 * @generated from service notification.NotificationService
 */
export const NotificationService = {
  typeName: "notification.NotificationService",
  methods: {
    /**
     * @generated from rpc notification.NotificationService.Subscribe
     */
    subscribe: {
      name: "Subscribe",
      I: SubscriptionRequest,
      O: Notification,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc notification.NotificationService.UpdateNotificationSettings
     */
    updateNotificationSettings: {
      name: "UpdateNotificationSettings",
      I: NotificationSettingsRequest,
      O: NotificationSettingsResponse,
      kind: MethodKind.Unary,
    },
  }
};

