// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/notification/notification_service.proto (package notification, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Notification, NotificationSettingsRequest, NotificationSettingsResponse, SubscriptionRequest } from "./notification_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service de notifications
 *
 * @generated from service notification.NotificationService
 */
export declare const NotificationService: {
  readonly typeName: "notification.NotificationService",
  readonly methods: {
    /**
     * @generated from rpc notification.NotificationService.Subscribe
     */
    readonly subscribe: {
      readonly name: "Subscribe",
      readonly I: typeof SubscriptionRequest,
      readonly O: typeof Notification,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc notification.NotificationService.UpdateNotificationSettings
     */
    readonly updateNotificationSettings: {
      readonly name: "UpdateNotificationSettings",
      readonly I: typeof NotificationSettingsRequest,
      readonly O: typeof NotificationSettingsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

