// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file user/user.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/user.proto.
 */
export const file_user_user: GenFile = /*@__PURE__*/
  fileDesc("Cg91c2VyL3VzZXIucHJvdG8SBHVzZXIiKAoVR2V0VXNlclByb2ZpbGVSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAkiMgoWR2V0VXNlclByb2ZpbGVSZXNwb25zZRIYCgR1c2VyGAEgASgLMgoudXNlci5Vc2VyIlEKGFVwZGF0ZVVzZXJQcm9maWxlUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJEhAKCHVzZXJuYW1lGAIgASgJEhIKCmF2YXRhcl91cmwYAyABKAkiPQoZVXBkYXRlVXNlclByb2ZpbGVSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkiWwoEVXNlchIKCgJpZBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRISCgphdmF0YXJfdXJsGAQgASgJEhIKCmNyZWF0ZWRfYXQYBSABKAkysAEKC1VzZXJTZXJ2aWNlEksKDkdldFVzZXJQcm9maWxlEhsudXNlci5HZXRVc2VyUHJvZmlsZVJlcXVlc3QaHC51c2VyLkdldFVzZXJQcm9maWxlUmVzcG9uc2USVAoRVXBkYXRlVXNlclByb2ZpbGUSHi51c2VyLlVwZGF0ZVVzZXJQcm9maWxlUmVxdWVzdBofLnVzZXIuVXBkYXRlVXNlclByb2ZpbGVSZXNwb25zZUIcCg1jb20uYWRpYS51c2VyQglVc2VyUHJvdG9QAWIGcHJvdG8z");

/**
 * @generated from message user.GetUserProfileRequest
 */
export type GetUserProfileRequest = Message<"user.GetUserProfileRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message user.GetUserProfileRequest.
 * Use `create(GetUserProfileRequestSchema)` to create a new message.
 */
export const GetUserProfileRequestSchema: GenMessage<GetUserProfileRequest> = /*@__PURE__*/
  messageDesc(file_user_user, 0);

/**
 * @generated from message user.GetUserProfileResponse
 */
export type GetUserProfileResponse = Message<"user.GetUserProfileResponse"> & {
  /**
   * @generated from field: user.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.GetUserProfileResponse.
 * Use `create(GetUserProfileResponseSchema)` to create a new message.
 */
export const GetUserProfileResponseSchema: GenMessage<GetUserProfileResponse> = /*@__PURE__*/
  messageDesc(file_user_user, 1);

/**
 * @generated from message user.UpdateUserProfileRequest
 */
export type UpdateUserProfileRequest = Message<"user.UpdateUserProfileRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string avatar_url = 3;
   */
  avatarUrl: string;
};

/**
 * Describes the message user.UpdateUserProfileRequest.
 * Use `create(UpdateUserProfileRequestSchema)` to create a new message.
 */
export const UpdateUserProfileRequestSchema: GenMessage<UpdateUserProfileRequest> = /*@__PURE__*/
  messageDesc(file_user_user, 2);

/**
 * @generated from message user.UpdateUserProfileResponse
 */
export type UpdateUserProfileResponse = Message<"user.UpdateUserProfileResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message user.UpdateUserProfileResponse.
 * Use `create(UpdateUserProfileResponseSchema)` to create a new message.
 */
export const UpdateUserProfileResponseSchema: GenMessage<UpdateUserProfileResponse> = /*@__PURE__*/
  messageDesc(file_user_user, 3);

/**
 * @generated from message user.User
 */
export type User = Message<"user.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string avatar_url = 4;
   */
  avatarUrl: string;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt: string;
};

/**
 * Describes the message user.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user_user, 4);

/**
 * @generated from service user.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.UserService.GetUserProfile
   */
  getUserProfile: {
    methodKind: "unary";
    input: typeof GetUserProfileRequestSchema;
    output: typeof GetUserProfileResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.UpdateUserProfile
   */
  updateUserProfile: {
    methodKind: "unary";
    input: typeof UpdateUserProfileRequestSchema;
    output: typeof UpdateUserProfileResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user_user, 0);

