// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file user/user.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/user.proto.
 */
export const file_user_user: GenFile = /*@__PURE__*/
  fileDesc("Cg91c2VyL3VzZXIucHJvdG8SBHVzZXIirQEKBFVzZXISCgoCaWQYASABKAQSEAoIdXNlcm5hbWUYAiABKAkSDQoFZW1haWwYAyABKAkSDwoHaXNBZG1pbhgEIAEoCBIXCg9pc0VtYWlsVmVyaWZpZWQYBSABKAgSEwoLaXNBY3RpdmF0ZWQYBiABKAgSEwoLaXNTdXNwZW5kZWQYByABKAgSEQoJY3JlYXRlZEF0GAggASgJEhEKCXVwZGF0ZWRBdBgJIAEoCSKaAQoRQ3JlYXRlVXNlclJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSDQoFZW1haWwYAiABKAkSEAoIcGFzc3dvcmQYAyABKAkSDwoHaXNBZG1pbhgEIAEoCBIXCg9pc0VtYWlsVmVyaWZpZWQYBSABKAgSEwoLaXNBY3RpdmF0ZWQYBiABKAgSEwoLaXNTdXNwZW5kZWQYByABKAgiHAoOR2V0VXNlclJlcXVlc3QSCgoCaWQYASABKAQiJgoVR2V0VXNlckJ5RW1haWxSZXF1ZXN0Eg0KBWVtYWlsGAEgASgJIpQBChFVcGRhdGVVc2VyUmVxdWVzdBIKCgJpZBgBIAEoBBIQCgh1c2VybmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIPCgdpc0FkbWluGAQgASgIEhcKD2lzRW1haWxWZXJpZmllZBgFIAEoCBITCgtpc0FjdGl2YXRlZBgGIAEoCBITCgtpc1N1c3BlbmRlZBgHIAEoCCIfChFEZWxldGVVc2VyUmVxdWVzdBIKCgJpZBgBIAEoBCIHCgVFbXB0eSJQChFMaXN0VXNlcnNSZXNwb25zZRIZCgV1c2VycxgBIAMoCzIKLnVzZXIuVXNlchIPCgdzdWNjZXNzGAMgASgIEg8KB21lc3NhZ2UYBCABKAkiSgoMVXNlclJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCRIYCgR1c2VyGAMgASgLMgoudXNlci5Vc2VyIi8KDFZQYXNzd29yZFJlcRINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIwCgxWUGFzc3dvcmRSZXMSDwoHbWVzc2FnZRgBIAEoCRIPCgdzdWNjZXNzGAIgASgIMqMDCgtVc2VyU2VydmljZRI5CgpDcmVhdGVVc2VyEhcudXNlci5DcmVhdGVVc2VyUmVxdWVzdBoSLnVzZXIuVXNlclJlc3BvbnNlEjMKB0dldFVzZXISFC51c2VyLkdldFVzZXJSZXF1ZXN0GhIudXNlci5Vc2VyUmVzcG9uc2USQQoOR2V0VXNlckJ5RW1haWwSGy51c2VyLkdldFVzZXJCeUVtYWlsUmVxdWVzdBoSLnVzZXIuVXNlclJlc3BvbnNlEjkKClVwZGF0ZVVzZXISFy51c2VyLlVwZGF0ZVVzZXJSZXF1ZXN0GhIudXNlci5Vc2VyUmVzcG9uc2USOQoKRGVsZXRlVXNlchIXLnVzZXIuRGVsZXRlVXNlclJlcXVlc3QaEi51c2VyLlVzZXJSZXNwb25zZRIxCglMaXN0VXNlcnMSCy51c2VyLkVtcHR5GhcudXNlci5MaXN0VXNlcnNSZXNwb25zZRI4Cg5WZXJpZnlQYXNzd29yZBISLnVzZXIuVlBhc3N3b3JkUmVxGhIudXNlci5WUGFzc3dvcmRSZXNCHAoNY29tLmFkaWEudXNlckIJVXNlclByb3RvUAFiBnByb3RvMw");

/**
 * @generated from message user.User
 */
export type User = Message<"user.User"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: bool isAdmin = 4;
   */
  isAdmin: boolean;

  /**
   * @generated from field: bool isEmailVerified = 5;
   */
  isEmailVerified: boolean;

  /**
   * @generated from field: bool isActivated = 6;
   */
  isActivated: boolean;

  /**
   * @generated from field: bool isSuspended = 7;
   */
  isSuspended: boolean;

  /**
   * @generated from field: string createdAt = 8;
   */
  createdAt: string;

  /**
   * @generated from field: string updatedAt = 9;
   */
  updatedAt: string;
};

/**
 * Describes the message user.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user_user, 0);

/**
 * @generated from message user.CreateUserRequest
 */
export type CreateUserRequest = Message<"user.CreateUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;

  /**
   * @generated from field: bool isAdmin = 4;
   */
  isAdmin: boolean;

  /**
   * @generated from field: bool isEmailVerified = 5;
   */
  isEmailVerified: boolean;

  /**
   * @generated from field: bool isActivated = 6;
   */
  isActivated: boolean;

  /**
   * @generated from field: bool isSuspended = 7;
   */
  isSuspended: boolean;
};

/**
 * Describes the message user.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_user_user, 1);

/**
 * @generated from message user.GetUserRequest
 */
export type GetUserRequest = Message<"user.GetUserRequest"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message user.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_user_user, 2);

/**
 * @generated from message user.GetUserByEmailRequest
 */
export type GetUserByEmailRequest = Message<"user.GetUserByEmailRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;
};

/**
 * Describes the message user.GetUserByEmailRequest.
 * Use `create(GetUserByEmailRequestSchema)` to create a new message.
 */
export const GetUserByEmailRequestSchema: GenMessage<GetUserByEmailRequest> = /*@__PURE__*/
  messageDesc(file_user_user, 3);

/**
 * @generated from message user.UpdateUserRequest
 */
export type UpdateUserRequest = Message<"user.UpdateUserRequest"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: bool isAdmin = 4;
   */
  isAdmin: boolean;

  /**
   * @generated from field: bool isEmailVerified = 5;
   */
  isEmailVerified: boolean;

  /**
   * @generated from field: bool isActivated = 6;
   */
  isActivated: boolean;

  /**
   * @generated from field: bool isSuspended = 7;
   */
  isSuspended: boolean;
};

/**
 * Describes the message user.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema: GenMessage<UpdateUserRequest> = /*@__PURE__*/
  messageDesc(file_user_user, 4);

/**
 * @generated from message user.DeleteUserRequest
 */
export type DeleteUserRequest = Message<"user.DeleteUserRequest"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message user.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export const DeleteUserRequestSchema: GenMessage<DeleteUserRequest> = /*@__PURE__*/
  messageDesc(file_user_user, 5);

/**
 * @generated from message user.Empty
 */
export type Empty = Message<"user.Empty"> & {
};

/**
 * Describes the message user.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_user_user, 6);

/**
 * @generated from message user.ListUsersResponse
 */
export type ListUsersResponse = Message<"user.ListUsersResponse"> & {
  /**
   * @generated from field: repeated user.User users = 1;
   */
  users: User[];

  /**
   * @generated from field: bool success = 3;
   */
  success: boolean;

  /**
   * @generated from field: string message = 4;
   */
  message: string;
};

/**
 * Describes the message user.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export const ListUsersResponseSchema: GenMessage<ListUsersResponse> = /*@__PURE__*/
  messageDesc(file_user_user, 7);

/**
 * @generated from message user.UserResponse
 */
export type UserResponse = Message<"user.UserResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: user.User user = 3;
   */
  user?: User;
};

/**
 * Describes the message user.UserResponse.
 * Use `create(UserResponseSchema)` to create a new message.
 */
export const UserResponseSchema: GenMessage<UserResponse> = /*@__PURE__*/
  messageDesc(file_user_user, 8);

/**
 * @generated from message user.VPasswordReq
 */
export type VPasswordReq = Message<"user.VPasswordReq"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message user.VPasswordReq.
 * Use `create(VPasswordReqSchema)` to create a new message.
 */
export const VPasswordReqSchema: GenMessage<VPasswordReq> = /*@__PURE__*/
  messageDesc(file_user_user, 9);

/**
 * @generated from message user.VPasswordRes
 */
export type VPasswordRes = Message<"user.VPasswordRes"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;
};

/**
 * Describes the message user.VPasswordRes.
 * Use `create(VPasswordResSchema)` to create a new message.
 */
export const VPasswordResSchema: GenMessage<VPasswordRes> = /*@__PURE__*/
  messageDesc(file_user_user, 10);

/**
 * @generated from service user.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.UserService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof UserResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof UserResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.GetUserByEmail
   */
  getUserByEmail: {
    methodKind: "unary";
    input: typeof GetUserByEmailRequestSchema;
    output: typeof UserResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.UpdateUser
   */
  updateUser: {
    methodKind: "unary";
    input: typeof UpdateUserRequestSchema;
    output: typeof UserResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.DeleteUser
   */
  deleteUser: {
    methodKind: "unary";
    input: typeof DeleteUserRequestSchema;
    output: typeof UserResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.ListUsers
   */
  listUsers: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof ListUsersResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.VerifyPassword
   */
  verifyPassword: {
    methodKind: "unary";
    input: typeof VPasswordReqSchema;
    output: typeof VPasswordResSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user_user, 0);

