// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file chat/chat.proto (package chat, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { User } from "../user/user_pb";
import { file_user_user } from "../user/user_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file chat/chat.proto.
 */
export const file_chat_chat: GenFile = /*@__PURE__*/
  fileDesc("Cg9jaGF0L2NoYXQucHJvdG8SBGNoYXQiIAoOUHJpdmF0ZUNvbnZSZXESDgoGdXNlcklkGAEgASgDIl4KDkdldFByaXZDb252UmVzEg8KB21lc3NhZ2UYASABKAkSDwoHc3VjY2VzcxgCIAEoCBIqCg9wcml2YXRlQ29udkxpc3QYAyADKAsyES5jaGF0LlByaXZhdGVDb252IiYKEUNyZWF0ZVByaXZDb252UmVxEhEKCW90aGVyVXNlchgBIAEoAyKSAQoLUHJpdmF0ZUNvbnYSCgoCaWQYASABKAMSHQoJb3RoZXJVc2VyGAIgASgLMgoudXNlci5Vc2VyEhMKC2xhc3RNZXNzYWdlGAMgASgJEhMKC3VucmVhZENvdW50GAQgASgFEi4KCmxhc3RVcGRhdGUYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIn8KCUdyb3VwQ29udhIKCgJpZBgBIAEoAxIMCgRuYW1lGAIgASgJEhMKC2xhc3RNZXNzYWdlGAMgASgJEhMKC3VucmVhZENvdW50GAQgASgFEi4KCmxhc3RVcGRhdGUYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIqYBCgdNZXNzYWdlEgoKAmlkGAEgASgDEg4KBnVzZXJJZBgCIAEoAxIWCg5jb252ZXJzYXRpb25JZBgDIAEoAxIMCgR0ZXh0GAQgASgJEg4KBmVkaXRlZBgFIAEoCBIjCgZzdGF0dXMYBiABKA4yEy5jaGF0Lk1lc3NhZ2VTdGF0dXMSEQoJY3JlYXRlZEF0GAcgASgJEhEKCXVwZGF0ZWRBdBgIIAEoCSIHCgVFbXB0eSoyCg1NZXNzYWdlU3RhdHVzEggKBFNFTlQQABINCglERUxJVkVSRUQQARIICgRSRUFEEAIqIgoIQ29udlR5cGUSCwoHUFJJVkFURRAAEgkKBUdST1VQEAEynQEKC0NoYXRTZXJ2aWNlEkUKF0dldFByaXZhdGVDb252ZXJzYXRpb25zEhQuY2hhdC5Qcml2YXRlQ29udlJlcRoULmNoYXQuR2V0UHJpdkNvbnZSZXMSRwoZQ3JlYXRlUHJpdmF0ZUNvbnZlcnNhdGlvbhIXLmNoYXQuQ3JlYXRlUHJpdkNvbnZSZXEaES5jaGF0LlByaXZhdGVDb252QiEKEmNvbS5hZGlhLmNoYXQuZ3JwY0IJQ2hhdFByb3RvUAFiBnByb3RvMw", [file_user_user, file_google_protobuf_timestamp]);

/**
 * @generated from message chat.PrivateConvReq
 */
export type PrivateConvReq = Message$1<"chat.PrivateConvReq"> & {
  /**
   * @generated from field: int64 userId = 1;
   */
  userId: bigint;
};

/**
 * Describes the message chat.PrivateConvReq.
 * Use `create(PrivateConvReqSchema)` to create a new message.
 */
export const PrivateConvReqSchema: GenMessage<PrivateConvReq> = /*@__PURE__*/
  messageDesc(file_chat_chat, 0);

/**
 * @generated from message chat.GetPrivConvRes
 */
export type GetPrivConvRes = Message$1<"chat.GetPrivConvRes"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: repeated chat.PrivateConv privateConvList = 3;
   */
  privateConvList: PrivateConv[];
};

/**
 * Describes the message chat.GetPrivConvRes.
 * Use `create(GetPrivConvResSchema)` to create a new message.
 */
export const GetPrivConvResSchema: GenMessage<GetPrivConvRes> = /*@__PURE__*/
  messageDesc(file_chat_chat, 1);

/**
 * @generated from message chat.CreatePrivConvReq
 */
export type CreatePrivConvReq = Message$1<"chat.CreatePrivConvReq"> & {
  /**
   * @generated from field: int64 otherUser = 1;
   */
  otherUser: bigint;
};

/**
 * Describes the message chat.CreatePrivConvReq.
 * Use `create(CreatePrivConvReqSchema)` to create a new message.
 */
export const CreatePrivConvReqSchema: GenMessage<CreatePrivConvReq> = /*@__PURE__*/
  messageDesc(file_chat_chat, 2);

/**
 * @generated from message chat.PrivateConv
 */
export type PrivateConv = Message$1<"chat.PrivateConv"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: user.User otherUser = 2;
   */
  otherUser?: User;

  /**
   * @generated from field: string lastMessage = 3;
   */
  lastMessage: string;

  /**
   * @generated from field: int32 unreadCount = 4;
   */
  unreadCount: number;

  /**
   * @generated from field: google.protobuf.Timestamp lastUpdate = 8;
   */
  lastUpdate?: Timestamp;
};

/**
 * Describes the message chat.PrivateConv.
 * Use `create(PrivateConvSchema)` to create a new message.
 */
export const PrivateConvSchema: GenMessage<PrivateConv> = /*@__PURE__*/
  messageDesc(file_chat_chat, 3);

/**
 * @generated from message chat.GroupConv
 */
export type GroupConv = Message$1<"chat.GroupConv"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string lastMessage = 3;
   */
  lastMessage: string;

  /**
   * @generated from field: int32 unreadCount = 4;
   */
  unreadCount: number;

  /**
   * @generated from field: google.protobuf.Timestamp lastUpdate = 8;
   */
  lastUpdate?: Timestamp;
};

/**
 * Describes the message chat.GroupConv.
 * Use `create(GroupConvSchema)` to create a new message.
 */
export const GroupConvSchema: GenMessage<GroupConv> = /*@__PURE__*/
  messageDesc(file_chat_chat, 4);

/**
 * Message
 *
 * @generated from message chat.Message
 */
export type Message = Message$1<"chat.Message"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 userId = 2;
   */
  userId: bigint;

  /**
   * @generated from field: int64 conversationId = 3;
   */
  conversationId: bigint;

  /**
   * @generated from field: string text = 4;
   */
  text: string;

  /**
   * @generated from field: bool edited = 5;
   */
  edited: boolean;

  /**
   * @generated from field: chat.MessageStatus status = 6;
   */
  status: MessageStatus;

  /**
   * @generated from field: string createdAt = 7;
   */
  createdAt: string;

  /**
   * @generated from field: string updatedAt = 8;
   */
  updatedAt: string;
};

/**
 * Describes the message chat.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_chat_chat, 5);

/**
 * @generated from message chat.Empty
 */
export type Empty = Message$1<"chat.Empty"> & {
};

/**
 * Describes the message chat.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_chat_chat, 6);

/**
 * Message status enum
 *
 * @generated from enum chat.MessageStatus
 */
export enum MessageStatus {
  /**
   * @generated from enum value: SENT = 0;
   */
  SENT = 0,

  /**
   * @generated from enum value: DELIVERED = 1;
   */
  DELIVERED = 1,

  /**
   * @generated from enum value: READ = 2;
   */
  READ = 2,
}

/**
 * Describes the enum chat.MessageStatus.
 */
export const MessageStatusSchema: GenEnum<MessageStatus> = /*@__PURE__*/
  enumDesc(file_chat_chat, 0);

/**
 * @generated from enum chat.ConvType
 */
export enum ConvType {
  /**
   * @generated from enum value: PRIVATE = 0;
   */
  PRIVATE = 0,

  /**
   * @generated from enum value: GROUP = 1;
   */
  GROUP = 1,
}

/**
 * Describes the enum chat.ConvType.
 */
export const ConvTypeSchema: GenEnum<ConvType> = /*@__PURE__*/
  enumDesc(file_chat_chat, 1);

/**
 * Service definition
 *
 * @generated from service chat.ChatService
 */
export const ChatService: GenService<{
  /**
   * @generated from rpc chat.ChatService.GetPrivateConversations
   */
  getPrivateConversations: {
    methodKind: "unary";
    input: typeof PrivateConvReqSchema;
    output: typeof GetPrivConvResSchema;
  },
  /**
   * @generated from rpc chat.ChatService.CreatePrivateConversation
   */
  createPrivateConversation: {
    methodKind: "unary";
    input: typeof CreatePrivConvReqSchema;
    output: typeof PrivateConvSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_chat_chat, 0);

