// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=js"
// @generated from file protos/notification/notification_service.proto (package notification, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/notification/notification_service.proto.
 */
export const file_protos_notification_notification_service: GenFile = /*@__PURE__*/
  fileDesc("Ci5wcm90b3Mvbm90aWZpY2F0aW9uL25vdGlmaWNhdGlvbl9zZXJ2aWNlLnByb3RvEgxub3RpZmljYXRpb24iJQoTU3Vic2NyaXB0aW9uUmVxdWVzdBIOCgZ1c2VySWQYASABKAkieQoMTm90aWZpY2F0aW9uEgoKAmlkGAEgASgJEg4KBnVzZXJJZBgCIAEoCRINCgV0aXRsZRgDIAEoCRIPCgdjb250ZW50GAQgASgJEgwKBHR5cGUYBSABKAkSEQoJdGltZXN0YW1wGAYgASgJEgwKBHJlYWQYByABKAgiZgobTm90aWZpY2F0aW9uU2V0dGluZ3NSZXF1ZXN0Eg4KBnVzZXJJZBgBIAEoCRITCgtlbmFibGVTb3VuZBgCIAEoCBIiChplbmFibGVEZXNrdG9wTm90aWZpY2F0aW9ucxgDIAEoCCIvChxOb3RpZmljYXRpb25TZXR0aW5nc1Jlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgy2AEKE05vdGlmaWNhdGlvblNlcnZpY2USTAoJU3Vic2NyaWJlEiEubm90aWZpY2F0aW9uLlN1YnNjcmlwdGlvblJlcXVlc3QaGi5ub3RpZmljYXRpb24uTm90aWZpY2F0aW9uMAEScwoaVXBkYXRlTm90aWZpY2F0aW9uU2V0dGluZ3MSKS5ub3RpZmljYXRpb24uTm90aWZpY2F0aW9uU2V0dGluZ3NSZXF1ZXN0Gioubm90aWZpY2F0aW9uLk5vdGlmaWNhdGlvblNldHRpbmdzUmVzcG9uc2VCLAoVY29tLmNoYXQubm90aWZpY2F0aW9uQhFOb3RpZmljYXRpb25Qcm90b1ABYgZwcm90bzM");

/**
 * Messages pour les abonnements
 *
 * @generated from message notification.SubscriptionRequest
 */
export type SubscriptionRequest = Message<"notification.SubscriptionRequest"> & {
  /**
   * @generated from field: string userId = 1;
   */
  userId: string;
};

/**
 * Describes the message notification.SubscriptionRequest.
 * Use `create(SubscriptionRequestSchema)` to create a new message.
 */
export const SubscriptionRequestSchema: GenMessage<SubscriptionRequest> = /*@__PURE__*/
  messageDesc(file_protos_notification_notification_service, 0);

/**
 * Messages pour les notifications
 *
 * @generated from message notification.Notification
 */
export type Notification = Message<"notification.Notification"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string userId = 2;
   */
  userId: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string content = 4;
   */
  content: string;

  /**
   * "MESSAGE", "GROUP", "SYSTEM"
   *
   * @generated from field: string type = 5;
   */
  type: string;

  /**
   * @generated from field: string timestamp = 6;
   */
  timestamp: string;

  /**
   * @generated from field: bool read = 7;
   */
  read: boolean;
};

/**
 * Describes the message notification.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export const NotificationSchema: GenMessage<Notification> = /*@__PURE__*/
  messageDesc(file_protos_notification_notification_service, 1);

/**
 * Messages pour les paramètres de notification
 *
 * @generated from message notification.NotificationSettingsRequest
 */
export type NotificationSettingsRequest = Message<"notification.NotificationSettingsRequest"> & {
  /**
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * @generated from field: bool enableSound = 2;
   */
  enableSound: boolean;

  /**
   * @generated from field: bool enableDesktopNotifications = 3;
   */
  enableDesktopNotifications: boolean;
};

/**
 * Describes the message notification.NotificationSettingsRequest.
 * Use `create(NotificationSettingsRequestSchema)` to create a new message.
 */
export const NotificationSettingsRequestSchema: GenMessage<NotificationSettingsRequest> = /*@__PURE__*/
  messageDesc(file_protos_notification_notification_service, 2);

/**
 * @generated from message notification.NotificationSettingsResponse
 */
export type NotificationSettingsResponse = Message<"notification.NotificationSettingsResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message notification.NotificationSettingsResponse.
 * Use `create(NotificationSettingsResponseSchema)` to create a new message.
 */
export const NotificationSettingsResponseSchema: GenMessage<NotificationSettingsResponse> = /*@__PURE__*/
  messageDesc(file_protos_notification_notification_service, 3);

/**
 * Service de notifications
 *
 * @generated from service notification.NotificationService
 */
export const NotificationService: GenService<{
  /**
   * @generated from rpc notification.NotificationService.Subscribe
   */
  subscribe: {
    methodKind: "server_streaming";
    input: typeof SubscriptionRequestSchema;
    output: typeof NotificationSchema;
  },
  /**
   * @generated from rpc notification.NotificationService.UpdateNotificationSettings
   */
  updateNotificationSettings: {
    methodKind: "unary";
    input: typeof NotificationSettingsRequestSchema;
    output: typeof NotificationSettingsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_protos_notification_notification_service, 0);

