// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/user/user_service.proto (package user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUserProfileRequest, GetUserProfileResponse, LoginRequest, LoginResponse, RegisterRequest, RegisterResponse, UpdateUserProfileRequest, UpdateUserProfileResponse } from "./user_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service user.UserService
 */
export declare const UserService: {
  readonly typeName: "user.UserService",
  readonly methods: {
    /**
     * @generated from rpc user.UserService.Register
     */
    readonly register: {
      readonly name: "Register",
      readonly I: typeof RegisterRequest,
      readonly O: typeof RegisterResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.UserService.Login
     */
    readonly login: {
      readonly name: "Login",
      readonly I: typeof LoginRequest,
      readonly O: typeof LoginResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.UserService.GetUserProfile
     */
    readonly getUserProfile: {
      readonly name: "GetUserProfile",
      readonly I: typeof GetUserProfileRequest,
      readonly O: typeof GetUserProfileResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.UserService.UpdateUserProfile
     */
    readonly updateUserProfile: {
      readonly name: "UpdateUserProfile",
      readonly I: typeof UpdateUserProfileRequest,
      readonly O: typeof UpdateUserProfileResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

