// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/user/user_service.proto (package user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUserProfileRequest, GetUserProfileResponse, LoginRequest, LoginResponse, RegisterRequest, RegisterResponse, UpdateUserProfileRequest, UpdateUserProfileResponse } from "./user_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service user.UserService
 */
export const UserService = {
  typeName: "user.UserService",
  methods: {
    /**
     * @generated from rpc user.UserService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.UserService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.UserService.GetUserProfile
     */
    getUserProfile: {
      name: "GetUserProfile",
      I: GetUserProfileRequest,
      O: GetUserProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.UserService.UpdateUserProfile
     */
    updateUserProfile: {
      name: "UpdateUserProfile",
      I: UpdateUserProfileRequest,
      O: UpdateUserProfileResponse,
      kind: MethodKind.Unary,
    },
  }
};

