// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=ts"
// @generated from file protos/user/user_service.proto (package user, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file protos/user/user_service.proto.
 */
export const file_protos_user_user_service = /*@__PURE__*/
  fileDesc("Ch5wcm90b3MvdXNlci91c2VyX3NlcnZpY2UucHJvdG8SBHVzZXIiRAoPUmVnaXN0ZXJSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJIjQKEFJlZ2lzdGVyUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIPCgdtZXNzYWdlGAIgASgJIi8KDExvZ2luUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSJaCg1Mb2dpblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCRINCgV0b2tlbhgDIAEoCRIYCgR1c2VyGAQgASgLMgoudXNlci5Vc2VyIigKFUdldFVzZXJQcm9maWxlUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJIjIKFkdldFVzZXJQcm9maWxlUmVzcG9uc2USGAoEdXNlchgBIAEoCzIKLnVzZXIuVXNlciJRChhVcGRhdGVVc2VyUHJvZmlsZVJlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRISCgphdmF0YXJfdXJsGAMgASgJIj0KGVVwZGF0ZVVzZXJQcm9maWxlUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIPCgdtZXNzYWdlGAIgASgJIlsKBFVzZXISCgoCaWQYASABKAkSEAoIdXNlcm5hbWUYAiABKAkSDQoFZW1haWwYAyABKAkSEgoKYXZhdGFyX3VybBgEIAEoCRISCgpjcmVhdGVkX2F0GAUgASgJMp0CCgtVc2VyU2VydmljZRI5CghSZWdpc3RlchIVLnVzZXIuUmVnaXN0ZXJSZXF1ZXN0GhYudXNlci5SZWdpc3RlclJlc3BvbnNlEjAKBUxvZ2luEhIudXNlci5Mb2dpblJlcXVlc3QaEy51c2VyLkxvZ2luUmVzcG9uc2USSwoOR2V0VXNlclByb2ZpbGUSGy51c2VyLkdldFVzZXJQcm9maWxlUmVxdWVzdBocLnVzZXIuR2V0VXNlclByb2ZpbGVSZXNwb25zZRJUChFVcGRhdGVVc2VyUHJvZmlsZRIeLnVzZXIuVXBkYXRlVXNlclByb2ZpbGVSZXF1ZXN0Gh8udXNlci5VcGRhdGVVc2VyUHJvZmlsZVJlc3BvbnNlQhwKDWNvbS5hZGlhLnVzZXJCCVVzZXJQcm90b1ABYgZwcm90bzM");

/**
 * Describes the message user.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_user_user_service, 0);

/**
 * Describes the message user.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_user_user_service, 1);

/**
 * Describes the message user.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_user_user_service, 2);

/**
 * Describes the message user.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_user_user_service, 3);

/**
 * Describes the message user.GetUserProfileRequest.
 * Use `create(GetUserProfileRequestSchema)` to create a new message.
 */
export const GetUserProfileRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_user_user_service, 4);

/**
 * Describes the message user.GetUserProfileResponse.
 * Use `create(GetUserProfileResponseSchema)` to create a new message.
 */
export const GetUserProfileResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_user_user_service, 5);

/**
 * Describes the message user.UpdateUserProfileRequest.
 * Use `create(UpdateUserProfileRequestSchema)` to create a new message.
 */
export const UpdateUserProfileRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_user_user_service, 6);

/**
 * Describes the message user.UpdateUserProfileResponse.
 * Use `create(UpdateUserProfileResponseSchema)` to create a new message.
 */
export const UpdateUserProfileResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_user_user_service, 7);

/**
 * Describes the message user.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/
  messageDesc(file_protos_user_user_service, 8);

/**
 * @generated from service user.UserService
 */
export const UserService = /*@__PURE__*/
  serviceDesc(file_protos_user_user_service, 0);

