// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=ts"
// @generated from file protos/auth/auth_service.proto (package auth, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file protos/auth/auth_service.proto.
 */
export const file_protos_auth_auth_service = /*@__PURE__*/
  fileDesc("Ch5wcm90b3MvYXV0aC9hdXRoX3NlcnZpY2UucHJvdG8SBGF1dGgiRAoPUmVnaXN0ZXJSZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJEhAKCHVzZXJuYW1lGAMgASgJIkQKEFJlZ2lzdGVyUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIPCgdtZXNzYWdlGAIgASgJEg4KBnVzZXJJZBgDIAEoCSIvCgxMb2dpblJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkihgEKDUxvZ2luUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIPCgdtZXNzYWdlGAIgASgJEg0KBXRva2VuGAMgASgJEhQKDHJlZnJlc2hUb2tlbhgEIAEoCRIOCgZ1c2VySWQYBSABKAkSEAoIdXNlcm5hbWUYBiABKAkSDAoEcm9sZRgHIAEoCSInChZUb2tlblZhbGlkYXRpb25SZXF1ZXN0Eg0KBXRva2VuGAEgASgJIkgKF1Rva2VuVmFsaWRhdGlvblJlc3BvbnNlEg8KB2lzVmFsaWQYASABKAgSDgoGdXNlcklkGAIgASgJEgwKBHJvbGUYAyABKAkiKwoTUmVmcmVzaFRva2VuUmVxdWVzdBIUCgxyZWZyZXNoVG9rZW4YASABKAkiTAoUUmVmcmVzaFRva2VuUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBINCgV0b2tlbhgCIAEoCRIUCgxyZWZyZXNoVG9rZW4YAyABKAkyjwIKC0F1dGhTZXJ2aWNlEjkKCFJlZ2lzdGVyEhUuYXV0aC5SZWdpc3RlclJlcXVlc3QaFi5hdXRoLlJlZ2lzdGVyUmVzcG9uc2USMAoFTG9naW4SEi5hdXRoLkxvZ2luUmVxdWVzdBoTLmF1dGguTG9naW5SZXNwb25zZRJMCg1WYWxpZGF0ZVRva2VuEhwuYXV0aC5Ub2tlblZhbGlkYXRpb25SZXF1ZXN0Gh0uYXV0aC5Ub2tlblZhbGlkYXRpb25SZXNwb25zZRJFCgxSZWZyZXNoVG9rZW4SGS5hdXRoLlJlZnJlc2hUb2tlblJlcXVlc3QaGi5hdXRoLlJlZnJlc2hUb2tlblJlc3BvbnNlQhwKDWNvbS5hZGlhLmF1dGhCCUF1dGhQcm90b1ABYgZwcm90bzM");

/**
 * Describes the message auth.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 0);

/**
 * Describes the message auth.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 1);

/**
 * Describes the message auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 2);

/**
 * Describes the message auth.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 3);

/**
 * Describes the message auth.TokenValidationRequest.
 * Use `create(TokenValidationRequestSchema)` to create a new message.
 */
export const TokenValidationRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 4);

/**
 * Describes the message auth.TokenValidationResponse.
 * Use `create(TokenValidationResponseSchema)` to create a new message.
 */
export const TokenValidationResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 5);

/**
 * Describes the message auth.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 6);

/**
 * Describes the message auth.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 7);

/**
 * Service d'authentification
 *
 * @generated from service auth.AuthService
 */
export const AuthService = /*@__PURE__*/
  serviceDesc(file_protos_auth_auth_service, 0);

