// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/auth/auth_service.proto (package auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginRequest, LoginResponse, RefreshTokenRequest, RefreshTokenResponse, RegisterRequest, RegisterResponse, TokenValidationRequest, TokenValidationResponse } from "./auth_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service d'authentification
 *
 * @generated from service auth.AuthService
 */
export const AuthService = {
  typeName: "auth.AuthService",
  methods: {
    /**
     * @generated from rpc auth.AuthService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.ValidateToken
     */
    validateToken: {
      name: "ValidateToken",
      I: TokenValidationRequest,
      O: TokenValidationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.RefreshToken
     */
    refreshToken: {
      name: "RefreshToken",
      I: RefreshTokenRequest,
      O: RefreshTokenResponse,
      kind: MethodKind.Unary,
    },
  }
};

