// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/auth/auth_service.proto (package auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LoginRequest, LoginResponse, RefreshTokenRequest, RefreshTokenResponse, RegisterRequest, RegisterResponse, TokenValidationRequest, TokenValidationResponse } from "./auth_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service d'authentification
 *
 * @generated from service auth.AuthService
 */
export declare const AuthService: {
  readonly typeName: "auth.AuthService",
  readonly methods: {
    /**
     * @generated from rpc auth.AuthService.Register
     */
    readonly register: {
      readonly name: "Register",
      readonly I: typeof RegisterRequest,
      readonly O: typeof RegisterResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.Login
     */
    readonly login: {
      readonly name: "Login",
      readonly I: typeof LoginRequest,
      readonly O: typeof LoginResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.ValidateToken
     */
    readonly validateToken: {
      readonly name: "ValidateToken",
      readonly I: typeof TokenValidationRequest,
      readonly O: typeof TokenValidationResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.RefreshToken
     */
    readonly refreshToken: {
      readonly name: "RefreshToken",
      readonly I: typeof RefreshTokenRequest,
      readonly O: typeof RefreshTokenResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

