// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/admin/admin_service.proto (package admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckRequest, CheckResponse, MessageActionRequest, MessageActionResponse, UserActionRequest, UserActionResponse, UserListRequest, UserListResponse } from "./admin_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service d'administration
 *
 * @generated from service admin.AdminService
 */
export const AdminService = {
  typeName: "admin.AdminService",
  methods: {
    /**
     * @generated from rpc admin.AdminService.GetAllUsers
     */
    getAllUsers: {
      name: "GetAllUsers",
      I: UserListRequest,
      O: UserListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.AdminService.BanUser
     */
    banUser: {
      name: "BanUser",
      I: UserActionRequest,
      O: UserActionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.AdminService.DeleteMessage
     */
    deleteMessage: {
      name: "DeleteMessage",
      I: MessageActionRequest,
      O: MessageActionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.AdminService.Check
     */
    check: {
      name: "Check",
      I: CheckRequest,
      O: CheckResponse,
      kind: MethodKind.Unary,
    },
  }
};

