// @generated by protoc-gen-es v2.2.5 with parameter "import_extension=ts"
// @generated from file protos/admin/admin_service.proto (package admin, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file protos/admin/admin_service.proto.
 */
export const file_protos_admin_admin_service = /*@__PURE__*/
  fileDesc("CiBwcm90b3MvYWRtaW4vYWRtaW5fc2VydmljZS5wcm90bxIFYWRtaW4iHAoMQ2hlY2tSZXF1ZXN0EgwKBGRhdGEYASABKAkiMAoNQ2hlY2tSZXNwb25zZRIOCgZzdGF0dXMYASABKAgSDwoHbWVzc2FnZRgCIAEoCSIuCg9Vc2VyTGlzdFJlcXVlc3QSDAoEcGFnZRgBIAEoBRINCgVsaW1pdBgCIAEoBSI9ChBVc2VyTGlzdFJlc3BvbnNlEhoKBXVzZXJzGAEgAygLMgsuYWRtaW4uVXNlchINCgV0b3RhbBgCIAEoBSJEChFVc2VyQWN0aW9uUmVxdWVzdBIOCgZ1c2VySWQYASABKAkSDwoHYWRtaW5JZBgCIAEoCRIOCgZyZWFzb24YAyABKAkiNgoSVXNlckFjdGlvblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCSJKChRNZXNzYWdlQWN0aW9uUmVxdWVzdBIRCgltZXNzYWdlSWQYASABKAkSDwoHYWRtaW5JZBgCIAEoCRIOCgZyZWFzb24YAyABKAkiOQoVTWVzc2FnZUFjdGlvblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCSJmCgRVc2VyEgoKAmlkGAEgASgJEg0KBWVtYWlsGAIgASgJEhAKCHVzZXJuYW1lGAMgASgJEgwKBHJvbGUYBCABKAkSEAoIaXNCYW5uZWQYBSABKAgSEQoJY3JlYXRlZEF0GAYgASgJMo4CCgxBZG1pblNlcnZpY2USPgoLR2V0QWxsVXNlcnMSFi5hZG1pbi5Vc2VyTGlzdFJlcXVlc3QaFy5hZG1pbi5Vc2VyTGlzdFJlc3BvbnNlEj4KB0JhblVzZXISGC5hZG1pbi5Vc2VyQWN0aW9uUmVxdWVzdBoZLmFkbWluLlVzZXJBY3Rpb25SZXNwb25zZRJKCg1EZWxldGVNZXNzYWdlEhsuYWRtaW4uTWVzc2FnZUFjdGlvblJlcXVlc3QaHC5hZG1pbi5NZXNzYWdlQWN0aW9uUmVzcG9uc2USMgoFQ2hlY2sSEy5hZG1pbi5DaGVja1JlcXVlc3QaFC5hZG1pbi5DaGVja1Jlc3BvbnNlQh4KDmNvbS5hZGlhLmFkbWluQgpBZG1pblByb3RvUAFiBnByb3RvMw");

/**
 * Describes the message admin.CheckRequest.
 * Use `create(CheckRequestSchema)` to create a new message.
 */
export const CheckRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_admin_admin_service, 0);

/**
 * Describes the message admin.CheckResponse.
 * Use `create(CheckResponseSchema)` to create a new message.
 */
export const CheckResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_admin_admin_service, 1);

/**
 * Describes the message admin.UserListRequest.
 * Use `create(UserListRequestSchema)` to create a new message.
 */
export const UserListRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_admin_admin_service, 2);

/**
 * Describes the message admin.UserListResponse.
 * Use `create(UserListResponseSchema)` to create a new message.
 */
export const UserListResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_admin_admin_service, 3);

/**
 * Describes the message admin.UserActionRequest.
 * Use `create(UserActionRequestSchema)` to create a new message.
 */
export const UserActionRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_admin_admin_service, 4);

/**
 * Describes the message admin.UserActionResponse.
 * Use `create(UserActionResponseSchema)` to create a new message.
 */
export const UserActionResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_admin_admin_service, 5);

/**
 * Describes the message admin.MessageActionRequest.
 * Use `create(MessageActionRequestSchema)` to create a new message.
 */
export const MessageActionRequestSchema = /*@__PURE__*/
  messageDesc(file_protos_admin_admin_service, 6);

/**
 * Describes the message admin.MessageActionResponse.
 * Use `create(MessageActionResponseSchema)` to create a new message.
 */
export const MessageActionResponseSchema = /*@__PURE__*/
  messageDesc(file_protos_admin_admin_service, 7);

/**
 * Describes the message admin.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/
  messageDesc(file_protos_admin_admin_service, 8);

/**
 * Service d'administration
 *
 * @generated from service admin.AdminService
 */
export const AdminService = /*@__PURE__*/
  serviceDesc(file_protos_admin_admin_service, 0);

