// @generated by protoc-gen-connect-es v1.6.1 with parameter "import_extension=ts"
// @generated from file protos/admin/admin_service.proto (package admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckRequest, CheckResponse, MessageActionRequest, MessageActionResponse, UserActionRequest, UserActionResponse, UserListRequest, UserListResponse } from "./admin_service_pbts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service d'administration
 *
 * @generated from service admin.AdminService
 */
export declare const AdminService: {
  readonly typeName: "admin.AdminService",
  readonly methods: {
    /**
     * @generated from rpc admin.AdminService.GetAllUsers
     */
    readonly getAllUsers: {
      readonly name: "GetAllUsers",
      readonly I: typeof UserListRequest,
      readonly O: typeof UserListResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.AdminService.BanUser
     */
    readonly banUser: {
      readonly name: "BanUser",
      readonly I: typeof UserActionRequest,
      readonly O: typeof UserActionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.AdminService.DeleteMessage
     */
    readonly deleteMessage: {
      readonly name: "DeleteMessage",
      readonly I: typeof MessageActionRequest,
      readonly O: typeof MessageActionResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.AdminService.Check
     */
    readonly check: {
      readonly name: "Check",
      readonly I: typeof CheckRequest,
      readonly O: typeof CheckResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

