// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=js"
// @generated from file protos/auth/auth_service.proto (package auth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protos/auth/auth_service.proto.
 */
export const file_protos_auth_auth_service: GenFile = /*@__PURE__*/
  fileDesc("Ch5wcm90b3MvYXV0aC9hdXRoX3NlcnZpY2UucHJvdG8SBGF1dGgiRAoPUmVnaXN0ZXJSZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJEhAKCHVzZXJuYW1lGAMgASgJIkQKEFJlZ2lzdGVyUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIPCgdtZXNzYWdlGAIgASgJEg4KBnVzZXJJZBgDIAEoCSIvCgxMb2dpblJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkihgEKDUxvZ2luUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIPCgdtZXNzYWdlGAIgASgJEg0KBXRva2VuGAMgASgJEhQKDHJlZnJlc2hUb2tlbhgEIAEoCRIOCgZ1c2VySWQYBSABKAkSEAoIdXNlcm5hbWUYBiABKAkSDAoEcm9sZRgHIAEoCSInChZUb2tlblZhbGlkYXRpb25SZXF1ZXN0Eg0KBXRva2VuGAEgASgJIkgKF1Rva2VuVmFsaWRhdGlvblJlc3BvbnNlEg8KB2lzVmFsaWQYASABKAgSDgoGdXNlcklkGAIgASgJEgwKBHJvbGUYAyABKAkiKwoTUmVmcmVzaFRva2VuUmVxdWVzdBIUCgxyZWZyZXNoVG9rZW4YASABKAkiTAoUUmVmcmVzaFRva2VuUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBINCgV0b2tlbhgCIAEoCRIUCgxyZWZyZXNoVG9rZW4YAyABKAkyjwIKC0F1dGhTZXJ2aWNlEjkKCFJlZ2lzdGVyEhUuYXV0aC5SZWdpc3RlclJlcXVlc3QaFi5hdXRoLlJlZ2lzdGVyUmVzcG9uc2USMAoFTG9naW4SEi5hdXRoLkxvZ2luUmVxdWVzdBoTLmF1dGguTG9naW5SZXNwb25zZRJMCg1WYWxpZGF0ZVRva2VuEhwuYXV0aC5Ub2tlblZhbGlkYXRpb25SZXF1ZXN0Gh0uYXV0aC5Ub2tlblZhbGlkYXRpb25SZXNwb25zZRJFCgxSZWZyZXNoVG9rZW4SGS5hdXRoLlJlZnJlc2hUb2tlblJlcXVlc3QaGi5hdXRoLlJlZnJlc2hUb2tlblJlc3BvbnNlQhwKDWNvbS5jaGF0LmF1dGhCCUF1dGhQcm90b1ABYgZwcm90bzM");

/**
 * Messages pour l'inscription
 *
 * @generated from message auth.RegisterRequest
 */
export type RegisterRequest = Message<"auth.RegisterRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;
};

/**
 * Describes the message auth.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 0);

/**
 * @generated from message auth.RegisterResponse
 */
export type RegisterResponse = Message<"auth.RegisterResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string userId = 3;
   */
  userId: string;
};

/**
 * Describes the message auth.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 1);

/**
 * Messages pour la connexion
 *
 * @generated from message auth.LoginRequest
 */
export type LoginRequest = Message<"auth.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 2);

/**
 * @generated from message auth.LoginResponse
 */
export type LoginResponse = Message<"auth.LoginResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string token = 3;
   */
  token: string;

  /**
   * @generated from field: string refreshToken = 4;
   */
  refreshToken: string;

  /**
   * @generated from field: string userId = 5;
   */
  userId: string;

  /**
   * @generated from field: string username = 6;
   */
  username: string;

  /**
   * @generated from field: string role = 7;
   */
  role: string;
};

/**
 * Describes the message auth.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 3);

/**
 * Messages pour la validation de token
 *
 * @generated from message auth.TokenValidationRequest
 */
export type TokenValidationRequest = Message<"auth.TokenValidationRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message auth.TokenValidationRequest.
 * Use `create(TokenValidationRequestSchema)` to create a new message.
 */
export const TokenValidationRequestSchema: GenMessage<TokenValidationRequest> = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 4);

/**
 * @generated from message auth.TokenValidationResponse
 */
export type TokenValidationResponse = Message<"auth.TokenValidationResponse"> & {
  /**
   * @generated from field: bool isValid = 1;
   */
  isValid: boolean;

  /**
   * @generated from field: string userId = 2;
   */
  userId: string;

  /**
   * @generated from field: string role = 3;
   */
  role: string;
};

/**
 * Describes the message auth.TokenValidationResponse.
 * Use `create(TokenValidationResponseSchema)` to create a new message.
 */
export const TokenValidationResponseSchema: GenMessage<TokenValidationResponse> = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 5);

/**
 * Messages pour le rafraîchissement de token
 *
 * @generated from message auth.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"auth.RefreshTokenRequest"> & {
  /**
   * @generated from field: string refreshToken = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 6);

/**
 * @generated from message auth.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"auth.RefreshTokenResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * @generated from field: string refreshToken = 3;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/
  messageDesc(file_protos_auth_auth_service, 7);

/**
 * Service d'authentification
 *
 * @generated from service auth.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.ValidateToken
   */
  validateToken: {
    methodKind: "unary";
    input: typeof TokenValidationRequestSchema;
    output: typeof TokenValidationResponseSchema;
  },
  /**
   * @generated from rpc auth.AuthService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_protos_auth_auth_service, 0);

